language: node_js
node_js:
  - "6"

branches:
  only:
    - master

dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_script:
  # Chrome settings
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run lint
  - npm run test.single
  - npm run e2e

after_success:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
